---
title: De qué hablamos cuando hablamos
author: Dave
date: '2021-08-24'
slug: de-que-hablamos
categories:
  - R
tags:
  - Data Cleansing
  - Text Analysis
  - Wordcloud
---

# Análisis y limpeza de textos.

Hola Ameyalli 😊, ¿alguna vez te has preguntado de qué hablamos cuando hablamos?, ¿habrá alguna palabra que más utilizas?

Bueno pues en este proyecto analizaremos nuestra conversación (que emoción) para tratar de identificar de qué es de lo que más hablamos, si usamos alguna palabra con mayor frecuencia, o bueno realmente buscaremos si sale algo interesante gg.

Antes de pasar al ejercicio te quiero platicar que el análisis de textos tiene muchas aplicaciones, por ejemplo qué diran los comentarios de las fotos de IG de una marca, o los comentarios de FB en un post publicitario. Ahora que están de moda los bots, se puede analizar qué es lo que le preguntan las personas al bot y usar eso para mejorarlo.

¿Te ha tocado responder alguna encuesta de satisfacción de una tienda comercial? Pues te imaginas tener que leer todos los comentarios, uno por uno, para saber de qué se queja la gente, que horror; pero justamente podemos usar el análisis de textos para identificar eso de forma rápida y casi que sin esfuerzo.

Pero bueno ahora sí vamos al ejercicio.